### PR TITLE
replace GraphQL Playground with GraphiQL

### PR DESCRIPTION
**Pull request by performantdata**
Also updates some library versions.

Follow-up to [Gitter](https://gitter.im/sangria-graphql/sangria?at=61157e637555e333510a2122).

### CODE REVIEW

**Comment by nickhudkins** [comment]
Hey!

I'd like to avoid adding another Java dependency here as I think it confuses the issue of what is the bare minimum to get a server running.

That said, I think it's great to move to the long-term supported GraphQL IDE. 

GraphiQL I believe provides a "CDN Bundle" which is simply the HTML file with the asset sources all served from a public CDN.

It should be as simply as simply replacing the HTML file that is already served, and updating the docs.

Hope that makes sense, and thanks for the contribution!

**Comment by performantdata** [comment]
@nickhudkins It's not a Java dependency. A [WebJar](https://www.webjars.org/) repackages a JavaScript module, NPM in these cases. But I suppose your argument is the same.

But by that argument, we shouldn't even include GraphiQL, because it's not necessary to stand up a Sangria server.

At my last job, we decided that GraphQL would be a good solution and, being a Scala shop, that Sangria would be too. But the obstacle to introducing it was that this example—which is what I based our service on—is far from complete. It would have been nice to see a Slick connection example (since we were using Slick, and I find it's often used with Akka). It would also have been nice to have a testing UI that doesn't depend on a public CDN, which is what I did here; it's not an easy thing to solve if you don't already know about WebJars.

In the same vein, effect libraries are popular now, so it'd be nice to see a `http4s` example and a `doobie` example, for instance. Having an example of how that's done could aid @yanns's [effort](https://gitter.im/sangria-graphql/sangria?at=61124dbb949a3d73862b64c0) to port to such libraries.

So we have opposing views of what this repo should be. Maybe it could be both, and everything? I could add flags to the `build.sbt` that users could set to include/exclude the CDN option? Something like that.

**Comment by nickhudkins** [comment]
I want to take a step back. It sounds like we (Sangria folk) could do a better job supporting folks getting started with it. I agree. I have heard this sentiment several times.

A proposal:

I believe there is value in providing a "sangria-http" framework, that is a base set of utilities, traits, etc.. that other libraries (sangria-akka-http, sangria-http4s-http) etc could leverage to provide a simpler integration experience with popular http libraries. I think this is probably a great place to start.

I think that the use of webjars to  distribute some static assets alongside these libraries makes plenty of sense in the context of a sangria-http library.

You are correct that we have different views on what **this** repository's responsibility is. We do not have the great fortune of having many active maintainers, so we have to be more pragmatic about what we choose to introduce, and where. 

In this example, no I do not believe it is beneficial to include packaging static assets and integrating with webjars as part of an example of integrating sangria and akka-http. 

Yes, you are right that by that logic, GraphQL IDE would be nowhere to be found if I took a purist approach to that, but I thought that the inclusion of a singular html file was a reasonable trade off.

**Comment by performantdata** [comment]
So, to recap, you believe that there's some value in having a super-small project (this one) to show how little code is needed to stand up a server, but you also recognize that people want more-practical examples. I don't really see the need for the former, and it could be generated from a generalized version of the latter, but… 🤷🏻

OK, so the CDN GraphiQL HTML goes here.

Then there's a new `sangria-http` library repo where the GraphiQL webjars stuff goes? Because I'm guessing that GraphiQL is both HTTP- **and** JSON-specific currently. I've seen that GraphQL Playground is in `sangria-akka-http`, but that doesn't seem like the right place for that even.

And where is the example (Giter8?) project that uses it? Yes, willing to start making this stuff. Because I do think that a UI is a sensible part of a GraphQL service, just like a Swagger UI is for a REST service, and that it's sensible for it to be self-contained with its static assets in the server.

Most of your repos appear to be libraries supporting data marshaling variants (`…marshalling-api`, `…argonaut`, `…circe`, `…ion`, `…jackson`, `…json4s-jackson`, `…json4s-native`, `…msgpack`, `…play-json`), HTTP interfacing (`…akka-http`), and programming paradigms (`…akka-streams`, `…rxscala`). Others are complete examples (`…akka-http-example`, `…playground`, `…relay-playground`, `…subscriptions-example`). Not sure why you're maintaining four example projects. This latter group I envision wrapping into a single Giter8 example with components swappable by the user after project generation. Not sure that I want to be the one to integrate all those components: I'm not a Play fan.

It seems like there's a need for a component diagram to give the big-picture view of these repos. Having an accurate picture often inspires cleaner design. I could also do that, just need a place to put it, which would probably be that hypothetical Giter8 repo.

**Comment by nickhudkins** [comment]
I can feel that you are pretty frustrated. Perhaps some time spent cleaning up docs, and older unmaintained examples would help. 

It might be worth having both a minimal, and a full featured example.

Feel free to message me directly on Gitter and we can talk about what a more full featured example looks like.

I think my most direct question is, will you volunteer to help maintain this larger example? I'm happy to help, but I can't do it alone.

**Comment by performantdata** [comment]
> will you volunteer to help maintain this larger example?

yes!

**Comment by performantdata** [comment]
This is waiting on https://github.com/sangria-graphql/sangria-akka-http/pull/12 to create a place for the GraphiQL webjars.

**Pull request closed without merging**
