### PR TITLE
General Updates

### PR DESCRIPTION
**Pull request by 8bitreid**
* Update Scala version to `2.12.10`
* add metals 
* update git ignore
* add type definitions

### CODE REVIEW

**Comment by yanns** [comment]
Hi @8bitreid 

this project was not active in the last months (https://github.com/sangria-graphql/sangria/issues/446#issuecomment-620175579).
If you want, you can now fix the conflicts so that I could merge your changes.

**Comment by nickhudkins** [comment]
Hey @8bitreid I just opened #18 , any opposition to closing this in favor of 2.13 support?

**Comment by nickhudkins** [comment]
Hey @8bitreid I'm gonna go ahead and close this, but thank you for pushing to get this updated. Feel free to take a look at the latest commits, we've updated everything to the newest versions that are generally available. Thanks!

**Comment by 8bitreid** [comment]
@nickhudkins wow, sorry I didn't see any of these comments 🙁 I'm very glad the update was made 👍🏻

**Pull request closed without merging**
